### ISSUE TITLE
Does not publish typescript declaration files

### ISSUE THREAD

**Issue by BenLorantfy** [KnapsackPro/knapsack-pro-js#99]
I'm following the guide [here](https://docs.knapsackpro.com/2020/how-to-build-native-integration-with-knapsack-pro-api-to-run-tests-in-parallel-for-any-test-runner-testing-framework) about creating a custom integration, but the `@knapsack-pro/core` does not publish the typescript declaration files.  Is it possible the build / publish process could be adjusted to publish them?

**Comment by ArturT** [comment]
Hi @BenLorantfy 

Are you asking about types here https://github.com/KnapsackPro/knapsack-pro-js/tree/main/packages/core/src/types
or do you have something else in mind?

**Comment by BenLorantfy** [comment]
hmm kind of.  Basically I get a typescript error whenever I import anything from `@knapsack-pro/core`:

<img width="1011" alt="image" src="https://github.com/user-attachments/assets/61a8c8e6-5d09-42b9-ac40-b4516b54ec38">

Which is because on `npm` there are no declaration files:

<img width="1722" alt="Screenshot 2024-12-02 at 9 52 23 PM" src="https://github.com/user-attachments/assets/ce9727e4-0c51-488d-b796-072b8bb76a92">

To fix this, I think `declaration: true` needs to be added to the `tsconfig.json` file

<img width="571" alt="image" src="https://github.com/user-attachments/assets/e9b0aac7-391e-4912-95a8-9bd0320696a8">

Then when you build it will output the `.d.ts` files:

<img width="350" alt="image" src="https://github.com/user-attachments/assets/578494bc-83dd-4c2a-bf72-01d5c37192e8">

And if you set `types` like this:

<img width="848" alt="image" src="https://github.com/user-attachments/assets/57a7bed0-7c1a-4f4a-bc3c-5d0598749312">

Then I no longer get typescript errors when importing: 

<img width="631" alt="image" src="https://github.com/user-attachments/assets/50b3b5b4-6d26-4691-b6c2-1eb961608bba">

**Comment by BenLorantfy** [comment]
I have created a PR for this here: https://github.com/KnapsackPro/knapsack-pro-js/pull/101

**Comment by 3v0k4** [comment]
Version 8.0.0 with declaration files is out on [npm](https://www.npmjs.com/package/@knapsack-pro/core/v/8.0.0).

Thanks for the contribution 🙏
